### ISSUE TITLE
기부 완료 페이지 구현

### ISSUE THREAD

**Issue by parkseonup** [teo-sprint-17/giboo-click#12]
## Feature 
기부 완료 페이지 구현

## Tasks
- [ ] 기부 결과 멘트 출력
- [ ] 응원 한 마디 입력창 구현
- [ ] 익명으로 기부하기 선택창 구현
